### ISSUE TITLE
Respuestas Beta 3.1.7

### ISSUE THREAD

**Issue by 7xu5** [hoksilato2/VAHoksiPack#16]
Al entregar una mision de las entrega de materiales en una estación (misiones con 2 flechas, el enunciado es la industria necesita x toneladas de ....... ).  Al entregar parte del mensaje lo dice en inglés.

"You have delivered 63 tonnes of Células madre to the mission depot.  Wing mission requirements are now completed."

**Comment by hoksilato2** [comment]
justo hace unos minutos he hecho cambios en la beta 3.1.7. mira de descargartelo de nuevo. Creo que es justo lo que he cambiado:

https://github.com/hoksilato2/VAHoksiPack/commit/1cbce66d440f59f2d28e16ee09ed3fd06f7cb17a

**Comment by 7xu5** [comment]
ok

**Comment by 7xu5** [comment]
Está perfecto ahora

**Comment by hoksilato2** [comment]
Perfecto, cierro issue.
