### ISSUE TITLE
Configurando velocidades

### ISSUE THREAD

**Issue by LoboEstelar** [hoksilato2/VAHoksiPack#20]
Hola Hoksilato! Soy Lobo Estelar. Supongo que este canal es mejor para el proyecto, pero dime si no es asi y no pongo cosas por aqui. 
El tema es la configuración de las velocidades de la nave. A mi me gusta usar argot naval, que en definitiva creo tambien se acabará utilizando en entorno espacial en los grandes buques. Para el control de la velocidad yo uso:
"Avante toda": Potencia al máximo
"Avante un cuarto": Potencia al 25%
"Avante media": Potencia al 50%

Para retroceder o frenar  utilizo dos:
"Atrás un Cuarto": hacia atrás 25%
"Atrás toda": hacia atrás 100%

"Parada": Parada total

**Comment by hoksilato2** [comment]
Me parece perfecto por aquí para mi es extremadamente más cómodo. 

Me pongo a ello para añadir esos comandos.

Por otro lado, te recuerdo a ver si podemos mirarnos el tema del soundizz. Sería muy interesante también tener los enlaces a las playlist de Spotify vinculadas a las de YouTube

**Comment by LoboEstelar** [comment]
En relación a lo de spotify te lo habia puesto por el foro, pero te lod ejo tambien por aqui:

Cantina espacial:
https://open.spotify.com/playlist/0O...hy6Vq3F1cPJufI

Música espacio suspense:
https://open.spotify.com/playlist/20...j0HPpWhV0b9soc

Música espacio profundo:
https://open.spotify.com/playlist/1S...aHm6jX1ZAno295

Música combate espacial
https://open.spotify.com/playlist/42...HvPpf9JG1E54vm

**Comment by hoksilato2** [comment]
Perdona Lobo, lo vi luego en el foro. Ya lo he puesto. Cierro este ticket. A disfrutar!!
