### ISSUE TITLE
Drones

### ISSUE THREAD

**Issue by 7xu5** [hoksilato2/VAHoksiPack#22]
Si un dron recoge algo del espacio y no tenemos la escotilla de carga despleglada nos dice algo así como recolección fallida porque la escotilla de carga está desplegada" y debería ser replegada o cerrada.

**Comment by hoksilato2** [comment]
No he podido reproducir este error. ¿Tú puedes? dime como plis.

**Comment by hoksilato2** [comment]
Si el problema persiste házmelo saber. mientras cierro.
