### ISSUE TITLE
Nombre de comandante

### ISSUE THREAD

**Issue by PerroAlfa** [hoksilato2/VAHoksiPack#24]
Buenas tardes, no se si estoy haciendo algo mal, pero el texto decia:

"HABILITA este script y pon aqui tu nombre", lo eh hecho pero me sigue llamando por el nombre que detecta de INARA...

¿Podrias darme una explicacion con "manzanas y peras" para que pueda entender que estoy haciendo mal?

Saludos y gracias anticipadas.

**Comment by hoksilato2** [comment]
Buenas @PerroAlfa. Espero que no haya ningún bug, lo probé en su momento, pero no lo he usado más. En principio lo que tienes que hacer es habilitar el script y en él mismo añadir el nombre. Eso debería reemplazar la variable del nombre de comandante. Deberías ver también el cambio en el log de VA. En la Wiki tienes un ejemplo, no se si te has pasado por ahí:

https://github.com/hoksilato2/VAHoksiPack/wiki/7.-Variables-Configurables#var-commander-name

El campo que tienes que modificar es el de "text" substituyendo la frase "HABILITA este script y pon aquí tu nombre" por el nombre que quieres que diga.

De todas formas, te lo reviso cuando esté en casa y te digo. No vaya a ser que no funcione!
