### ISSUE TITLE
Error cargando plugin.

### ISSUE THREAD

**Issue by sonozaki** [hoksilato2/VAHoksiPack#26]
He instalado Voice Attack con HoksiPack, casi todo funciona correctamente, salvo algunos comandos como los relacionados con poner música no funcionan y me aparece el error "UNABLE TO INVOKE PLUGIN. PLUGIN NOT AVAILABLE." he reparado la instalación, me he asegurado de que "apps folder" apunta a la ruta correcta donde están instalados los plugins, en plugins manager también se pueden ver los plugins activados etc... 

¿Qué podría ser?

**Comment by hoksilato2** [comment]
El problema principal seguramente sea el complemento del EliteG19s. Parece ser que el desarrollador la lio un poco en su última versión. Te diría que probases de desinstalar la aplicación y volverla a instalar haciendo lo que él dice aquí:

https://forums.frontier.co.uk/threads/elite-g19s-companion-app-with-simulated-space-traffic-control.226782/post-8634807

También revisa en VoiceAttack, en Opciones -> general -> Plugin Manager que tengas todos los complementos necesarios:

bindED
EDDI
EliteG19s
VA Extensions

Dime a ver!

**Comment by sonozaki** [comment]
Voice Atack lo tengo instalado desde Steam. He mirado en el plugin manager y no aparece listado el EliteG19s. En la carpeta Apps de voice attack, tengo todos los plugins, salvo el EliteG19s, he intentado repararlo, pero HoksiPack no me permite modificar la ruta de instalación de EliteG19s

¿Como muevo el plugin a la carpeta apps de voice attack?

**Comment by hoksilato2** [comment]
Vale, la solución manual es esta:
    1. Ir a la carpeta donde se instala EliteG19s (%LOCALAPPDATA%\Programs\EliteG19s)
    2. Verás que hay una carpeta que se llama VoiceAttack. Allí dentro está la carpeta Apps como la de VA, y dentro la carpeta que el instalador debería copiar automáticamente dentro de la carpeta de instalación del VA.
    3. Cópiala dentro de la carpeta "Apps" de tu VoiceAttack en Steam y reinicia VA. Debería funcionarte así.

De todos modos, me interesa saber porque no se te instala. Antes de probar esta solución, podrías probar de reinstalar G19s con el instalador oficial? Lo puedes descargar de [aquí](https://apps.magicmau.nl/EliteG19s/EliteG19s-latest.msi). Es el mismo que lleva el Hoksipack pero sin tener instalación silenciosa. Si tu navegador te avisa de que no es una aplicación de confianza, descárgalo igual. El desarrollador no la tiene firmada (como yo tampoco tengo el hoksipack).

Cuéntame que tal te ha ido, vale? :)

**Comment by sonozaki** [comment]
> 
> 
> Vale, la solución manual es esta:
> 1. Ir a la carpeta donde se instala EliteG19s (%LOCALAPPDATA%\Programs\EliteG19s)
> 2. Verás que hay una carpeta que se llama VoiceAttack. Allí dentro está la carpeta Apps como la de VA, y dentro la carpeta que el instalador debería copiar automáticamente dentro de la carpeta de instalación del VA.
> 3. Cópiala dentro de la carpeta "Apps" de tu VoiceAttack en Steam y reinicia VA. Debería funcionarte así.
> 
> De todos modos, me interesa saber porque no se te instala. Antes de probar esta solución, podrías probar de reinstalar G19s con el instalador oficial? Lo puedes descargar de [aquí](https://apps.magicmau.nl/EliteG19s/EliteG19s-latest.msi). Es el mismo que lleva el Hoksipack pero sin tener instalación silenciosa. Si tu navegador te avisa de que no es una aplicación de confianza, descárgalo igual. El desarrollador no la tiene firmada (como yo tampoco tengo el hoksipack).
> 
> Cuéntame que tal te ha ido, vale? :)
> 
> PD: Ahora mismo no te desilusiones si no tienes cuenta Premium de Spotify. El EliteG19s está roto en cuanto a música de Youtube. En principio puedes cambiar de proveedor de música diciendo "cambia a spotify/youtube" pero ya te digo, hasta que no lo arreglen el de youtube no va :(

Me ha funcionado de la forma en que me has dicho, de hecho me funciona G19s con youtube. He arrancado el instalador que me has dicho, y parece completamente distinto, ¿Tal vez no sea el mismo instalador? Al instentar reinstalarlo me ha dado un error genérico, no daba muchos detalles, supongo que debe ser porque detecta que ya está instalado.

Gracias por la ayuda, y como digo, me funciona perfectamente G19s con youtube.

Tal vez sea offtopic, pero si tuviese spotify premium, ¿Se podría controlar con voice attack? Es decir, que yo le dijese "pon cancion X de la banda Y"?

**Comment by hoksilato2** [comment]
Si, con Spotify es como lo uso yo. Pero los controles son los mismos que con Youtube. Puedes decirle que de ponga X lista de reproducción siempre y cuando la hayas puesto en el G19s. No es como una Alexa. De todos modos, si quisieras podrías instalarte Alexa en el PC para ese cometido. O creo que Cortana también puede ponerte la canción que quieras de Spotify. 

Cierro el ticket y disculpa que he estado muy out. Cosas de la paternidad :)
