### ISSUE TITLE
Errores detectados en varias respuestas

### ISSUE THREAD

**Issue by 7xu5** [hoksilato2/VAHoksiPack#8]
** Al cambiar de nave y sin llevar srv ni caza me dice que los tengo en la nave. 
** Al llegar a un sistema en el reporte dice: "ya no estas en espacio de ninguno","comandante ha llegado a espacio de none" 
** Al decir la población en el reporte del sistema dice cien mil de habitantes EJ:sothis
** Al cobrar las misiones de pasajeros dice "pago de mas allá de dos y medio millon de creditos"

**Comment by hoksilato2** [comment]
En el Json, cuando una cifra se engloba en la función "Humanise" lo que hace es tirar de unas expresiones traducidas en el programa EDDI (proyecto en crowdin). Quizás deberíamos mirar que expresiones se adecuan más para que no se líe tanto en decir cifras aproximadas.

El tema del reporte al llegar al sistema debería estar ya solucionado.

El error en el cambio de nave creo que es un bug de la versión de EDDI, no me he dado cuenta de si sigue pasando.

**Comment by 7xu5** [comment]
vendría bien revisar el humanise ese porque dice cosas que no cuadran. ¿ahí está tambien metido como dice los números? pregunto por lo que dice de "diez y medio millon de años" por ejemplo

**Comment by hoksilato2** [comment]
Correcto. Cogeré las variables que hay e intentamos montar frases con los numeros a ver cuál es la mejor combinación

**Comment by hoksilato2** [comment]
Vamos a ver como lo hacemos,

La cosa está en que tenemos esta lista de expresiones. Pongo el nombre de la variable que coincide con el significado de la expresión sin espacios y abajo la traducción que hice:

```
andahalf
     y medio de 

  around
    alrededor de 

  billion
    millardo

  dash
     guión 

  justover
    un poco mas de 

  million
    millón

  minus
     menos de 

  nearly
    cerca de 

  onthewayto
    casi 

  over
    más allá de 

  plus
     mas 

  point
     punto 

  quadrillion
    cuatrillón

  
  thousand
    mil

  
  trillion
    trillón

  wellover
    mucho más allá de 

  zero
    cero
```

Con esto y los números EDDI monta las "humanizaciones" para dar cifras aproximadas y no complicarse con cifras exactas. Por ejemplo en lugar de "diez y medio millon de años" debería ser "diez millones y medio de años". El problema es que el medio va después del millones pero el medio forma parte del número. es decir: 10.500.000 de años

Por otro lado, el cambiar millón por millones si se debe hacer en el script de EDDI. como ya he hecho en muchos eventos. Hay que localizar donde no pluraliza correctamente. Hay que añadir una función que dice:

Si años es superior a 1.999.999, añadir "es" al final de la frase.

Lo mismo con miles, cientos,...

y por último está el tema de la traducción de "billion" que no es billón verdad? es mil millones pero no recuerdo porque lo traducí como "millardo". ¿Está bien millardo?

**Comment by hoksilato2** [comment]
En realidad ya lo tuve en cuenta. Está traducido como "millón" porque en el script de EDDI podamos añadir "es" al final siempre y cuando la variable supere el 1.999.999. De la otra forma deberíamos quitar caracteres y no se puede. Bueno podríamos hacer una excepción pero es escribir más porque si creo.

Yo millardo lo traduciría por "mil millones", el problema es el "un" cuando es uno. no dices "un mil millones" pero si "un millardo", entonces nose... Pero cuando Shirka habla de millardos a mi me suena fatal.

El problema viene con los "mucho mas allá" "un poco mas de", etc... nose, hay que mirarlo bien, pero tal como dices, lo mejor será ir haciendo pruebas con el script de "system report".

**Comment by hoksilato2** [comment]
Oh Txus!! Lo de coma 5 es una genialidad de lo sencilla que es la solución. Voy a poner esos cambios. En principio en la siguiente versión de eddi deberíamos ver los cambios. A ver como queda :)

**Comment by hoksilato2** [comment]
Hay que mirarse bien de nuevo esto. En ocasiones dice 2 millón de créditos. Toca localizar las entradas donde no está metida la excepción:
 > 1:es}

Un ejemplo está en el evento "Limped sold" que allí lo pusímos.

**Comment by hoksilato2** [comment]
Cierro esto, pero añado a cosas pendientes terminar de revisar los plurales.
