### ISSUE TITLE
Respuestas en exploración

### ISSUE THREAD

**Issue by 7xu5** [hoksilato2/VAHoksiPack#9]
* Al llegar a un sistema igual deberíamos quitar información ya que en algunos casos se repite demasiadas veces la palabra comandante cuando te informa de las veces que has estado allí. Por ejemplo dice "esta es tu primera visita al sistema, Bienvenido de nuevo comandante","comandante ha llegado a ninguno, bienvenido de nuevo comandante" no tiene sentido.
* En el reporte de los materiales de los planetas los dice en ingles - Si me dices donde estan los traduzco, o si me pasas el archivo tambien.
* En el reporte del sistema los nombes de la powerplay salen en ingles - lo mismo de arriba

**Comment by hoksilato2** [comment]
He corregido algunos puntos en la 3.1.6, pero el sistema de traducción de variables para algo inestable. Si alguien en cottle me sabe decir como hacer para que diga una frase tanto si el resultado de una variable es una cosa u otra que me lo diga. No consigo que me funcione con "||" ni con "&&"

**Comment by 7xu5** [comment]
ok Funciona muy bien el cambio, en lo de cottle no tengo ni idea

**Comment by hoksilato2** [comment]
Están quitando variables por la parte del servidor y añadiéndolas en la app. Cierro issue, debería solucionarse con la nueva traducción.

**Comment by LoboEstelar** [comment]
Sugerencia, amigo mio. Lo primero, excelentes los datos de exploración que proporciona, ahora completamente traducidos y bien expresados. Sin embargo, como explorador, y dado que me meto en modo scaneo a lo bestia ocurre lo que supongo le ocurre a los otros compañeros. La computadora se pone a hablar en plan metralleta, me he ido ya del sistema y sigue hablando. Habla tanto que ya no le haces caso (esa habilidad que tenemos los hombres para desconectar cuando una mujer nos habla demasiado). Pero se me ha ocurrido una cosa que creo que podria ser interesante. Realmente hay una serie de cosas solo que interesan cuando escaneas, que no se si podrá proporcionarlo el sistema:

1.- Nombre del planeta
2.- si hay señales interesantes en él
3.- Creditos ganados 

Esta información se podría dar con el escaneo del sistema. La otra información, más específica y abundante, se podria dar cuando se mapea el planeta. El mapeo es algo más lento y daría tiempo, entre planeta y planeta, a que shirka dijera todo lo que tiene que decir. Creo que así alcanzariamos un equilibrio entre efectividad y comodidad. ¿Tu que dices?
